stages:
  - build_test
  - deploy

before_script:
  - apt-get update -qy
  - apt-get install -y git python3 python3-dev python3-pip
  - python3 -m pip install --upgrade pip

pytest:
  stage: build_test
  image: tensorflow/tensorflow:2.0.1-py3
  script:
  - python3 -m pip install .[test]
  - py.test --benchmark-disable --cov=tf_pwa --doctest-modules tf_pwa

pylint:
  stage: build_test
  image: tensorflow/tensorflow:2.0.1-py3
  script:
  - python3 -m pip install .[dev]
  - pylint tf_pwa --errors-only --exit-zero
  - pylint tf_pwa -E --disable=all -e E0602


build_docs:
  stage: deploy
  only:
    - tags
    - triggers
    - schedules
  script:
    - apt-get install -y make texlive-full
    - python3 -m pip install .[doc]
    - cd docs && make latexpdf
  allow_failure: true
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - docs/_build/latex/*.pdf

pages:
  stage: deploy
  script:
    - python3 -m pip install .[doc]
    - python3 setup.py build_sphinx
    - cp build/sphinx/html public -R
    - python3 setup.py bdist_wheel
    - cp dist/*.whl public/
  artifacts:
    paths:
      - public
