stages:
  - build_test

pytest:
  stage: build_test
  image: tensorflow/tensorflow:2.0.1-py3
  script:
  - pip install numpy scipy sympy matplotlib
  - pip install pysnooper pytest pytest-cov pytest-benchmark
  - py.test --benchmark-disable --cov=tf_pwa

build_wheel:
  stage: build_test
  script:
  - apt-get update -qy
  - apt-get install -y python3-dev python3-pip
  - pip3 install setuptools
  - python3 setup.py bdist_wheel

  artifacts:
    untracked: true

build_docs:
  stage: build_test
  only:
  - tags
  - triggers
  - schedules
  script:
  - apt-get update -qy
  - apt-get install -y python3 python3-dev python3-pip make texlive
  - pip3 install setuptools sphinx numpy scipy matplotlib pyyaml
  - cd docs && make latexpdf
  allow_failure: true
  artifacts:
    untracked: true
