stages:
  - build
  - test

pytest:
  stage: test
  image: conda/miniconda3
  script:
  - conda install pytest numpy scipy sympy tensorflow pytest-cov
  - py.test --cov=tf_pwa

build_wheel:
  stage: build
  script:
  - apt-get update -qy
  - apt-get install -y python3-dev python3-pip
  - pip3 install setuptools
  - python3 setup.py bdist_wheel

  artifacts:
    untracked: true
